# Generated by Django 5.1.6 on 2025-02-25 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comentario', models.TextField(verbose_name='Comentario que ha dejado en la web')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de creación')),
                ('contactado', models.BooleanField(default=False, verbose_name='¿Se ha contactado con él?')),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], default='ES', max_length=2),
        ),
    ]
