# Generated by Django 5.1.6 on 2025-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_contacto_comentario_alter_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='premios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
