# Generated by Django 5.1.6 on 2025-02-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_autor_premios_alter_autor_sitio_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
